apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-deployment.yaml
  - api-gateway-hpa.yaml

configMapGenerator:
  - name: ride-sharing-runtime
    literals:
      - APP_ENV=local
      - AUTH_REQUIRED=false
      - AUTH_ISSUER=
      - AUTH_AUDIENCE=
      - AUTH_TOKEN_USE=access
      - DRIVER_LOCATION_REDIS_SECRET_ID=

generatorOptions:
  disableNameSuffixHash: true
